name: build docker images
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          VERSION="latest"
          TAG="${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_SPACE}}"
          IMAGE="${{secrets.IMAGE_NAME}}"
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWD }} ${{secrets.DOCKER_REGISTRY}}
          docker build --target runner -t "${TAG}/${IMAGE}:${VERSION}" .
          docker push "${TAG}/${IMAGE}:${VERSION}"